### ISSUE TITLE
Implement REST API calls in contribution `install` method

### ISSUE THREAD

**Issue by danielwatson6** [semantic-ai/tfbuild#10]
See `src/tfbuild/repository.py`.

Right now we install a placeholder. Replace it with an actual call to the REST API that fetches the contribution by name. This probably requires writing a request handler outside this repository too.

**Comment by marksurnin** [comment]
Basic implementation in https://github.com/semantic-ai/tfbuild/commit/241ef0776ebde028aab18f4c704b6eb780cc429d.
