### ISSUE TITLE
Config file for tfbuild repo dependencies

### ISSUE THREAD

**Issue by danielwatson6** [semantic-ai/tfbuild#16]
Akin to a `requirements.txt` or a `package.json` file, but for contributions. This would allow (and should be implemented to resolve this issue):
1. Specifying a project's dependencies
2. Installing / uninstalling them with a single CLI command

I suggest something like `requirements.txt` where each line is of the form `author:contrib_name==version` (or `>=`, etc)

**Comment by marksurnin** [comment]
After #13.

**Comment by marksurnin** [comment]
Implemented in 896b6b7.
