### ISSUE TITLE
More CLI commands

### ISSUE THREAD

**Issue by danielwatson6** [semantic-ai/tfbuild#22]
1. `list`: should output one line `[author]:[slug]==[version]` for each saved contribution directory
2. `install_local [path_to_python_file]`: should just `cp` the argument to `~/.tfbuild/saves/[username]/[filename_minus_extension]/[filename_with_extension]`
3. `saves list`: should output one line `[dirname] ([directory size in MB/GB])` for each saved model directory
4. `saves delete [dirname]`: should prompt for confirmation and `rm -rf ~/.tfbuild/saves/[dirname]`

**Comment by marksurnin** [comment]
I missed this! Let's discuss this today.
